//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SistFacturacion.Areas.Facturacion.Models.sistemafactura
{

    [Persistent(@"Tbl_Cat_ProductosServicios")]
    public partial class Cat_ProductosServicios : XPLiteObject
    {
        int fPk_ProductoServicio;
        [Key(true)]
        public int Pk_ProductoServicio
        {
            get { return fPk_ProductoServicio; }
            set { SetPropertyValue<int>(nameof(Pk_ProductoServicio), ref fPk_ProductoServicio, value); }
        }
        int fPk_Empresa;
        public int Pk_Empresa
        {
            get { return fPk_Empresa; }
            set { SetPropertyValue<int>(nameof(Pk_Empresa), ref fPk_Empresa, value); }
        }
        int fClave_ProdServ_SAT;
        public int Clave_ProdServ_SAT
        {
            get { return fClave_ProdServ_SAT; }
            set { SetPropertyValue<int>(nameof(Clave_ProdServ_SAT), ref fClave_ProdServ_SAT, value); }
        }
        string fClave_Ident;
        [Size(SizeAttribute.Unlimited)]
        public string Clave_Ident
        {
            get { return fClave_Ident; }
            set { SetPropertyValue<string>(nameof(Clave_Ident), ref fClave_Ident, value); }
        }
        string fCodigoBarras;
        [Size(SizeAttribute.Unlimited)]
        public string CodigoBarras
        {
            get { return fCodigoBarras; }
            set { SetPropertyValue<string>(nameof(CodigoBarras), ref fCodigoBarras, value); }
        }
        int fClave_Unidad_SAT;
        public int Clave_Unidad_SAT
        {
            get { return fClave_Unidad_SAT; }
            set { SetPropertyValue<int>(nameof(Clave_Unidad_SAT), ref fClave_Unidad_SAT, value); }
        }
        string fUnidad;
        [Size(SizeAttribute.Unlimited)]
        public string Unidad
        {
            get { return fUnidad; }
            set { SetPropertyValue<string>(nameof(Unidad), ref fUnidad, value); }
        }
        string fDescripcion_ProdServ_Base;
        [Size(SizeAttribute.Unlimited)]
        public string Descripcion_ProdServ_Base
        {
            get { return fDescripcion_ProdServ_Base; }
            set { SetPropertyValue<string>(nameof(Descripcion_ProdServ_Base), ref fDescripcion_ProdServ_Base, value); }
        }
        decimal fPrecioBase;
        public decimal PrecioBase
        {
            get { return fPrecioBase; }
            set { SetPropertyValue<decimal>(nameof(PrecioBase), ref fPrecioBase, value); }
        }
        string fIVAT;
        [Size(SizeAttribute.Unlimited)]
        public string IVAT
        {
            get { return fIVAT; }
            set { SetPropertyValue<string>(nameof(IVAT), ref fIVAT, value); }
        }
        string fIEPST;
        [Size(SizeAttribute.Unlimited)]
        public string IEPST
        {
            get { return fIEPST; }
            set { SetPropertyValue<string>(nameof(IEPST), ref fIEPST, value); }
        }
        string fIVAR;
        [Size(SizeAttribute.Unlimited)]
        public string IVAR
        {
            get { return fIVAR; }
            set { SetPropertyValue<string>(nameof(IVAR), ref fIVAR, value); }
        }
        string fISRR;
        [Size(SizeAttribute.Unlimited)]
        public string ISRR
        {
            get { return fISRR; }
            set { SetPropertyValue<string>(nameof(ISRR), ref fISRR, value); }
        }
        string fIEstatal;
        [Size(SizeAttribute.Unlimited)]
        public string IEstatal
        {
            get { return fIEstatal; }
            set { SetPropertyValue<string>(nameof(IEstatal), ref fIEstatal, value); }
        }
        string fOtraRetencion;
        [Size(SizeAttribute.Unlimited)]
        public string OtraRetencion
        {
            get { return fOtraRetencion; }
            set { SetPropertyValue<string>(nameof(OtraRetencion), ref fOtraRetencion, value); }
        }
    }

}
