//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SistFacturacion.Areas.Facturacion.Models.sistemafactura
{

    [Persistent(@"Tbl_CFDIs")]
    public partial class CFDIs : XPLiteObject
    {
        int fPk_CFDI;
        [Key(true)]
        public int Pk_CFDI
        {
            get { return fPk_CFDI; }
            set { SetPropertyValue<int>(nameof(Pk_CFDI), ref fPk_CFDI, value); }
        }
        string fSerie;
        [Size(SizeAttribute.Unlimited)]
        public string Serie
        {
            get { return fSerie; }
            set { SetPropertyValue<string>(nameof(Serie), ref fSerie, value); }
        }
        int fFolio;
        public int Folio
        {
            get { return fFolio; }
            set { SetPropertyValue<int>(nameof(Folio), ref fFolio, value); }
        }
        int fPk_Plantilla;
        public int Pk_Plantilla
        {
            get { return fPk_Plantilla; }
            set { SetPropertyValue<int>(nameof(Pk_Plantilla), ref fPk_Plantilla, value); }
        }
        string fRFC_Emisor;
        [Size(SizeAttribute.Unlimited)]
        public string RFC_Emisor
        {
            get { return fRFC_Emisor; }
            set { SetPropertyValue<string>(nameof(RFC_Emisor), ref fRFC_Emisor, value); }
        }
        string fRFC_Receptor;
        [Size(SizeAttribute.Unlimited)]
        public string RFC_Receptor
        {
            get { return fRFC_Receptor; }
            set { SetPropertyValue<string>(nameof(RFC_Receptor), ref fRFC_Receptor, value); }
        }
        int fPk_Empresa;
        public int Pk_Empresa
        {
            get { return fPk_Empresa; }
            set { SetPropertyValue<int>(nameof(Pk_Empresa), ref fPk_Empresa, value); }
        }
        string fXML;
        [Size(SizeAttribute.Unlimited)]
        public string XML
        {
            get { return fXML; }
            set { SetPropertyValue<string>(nameof(XML), ref fXML, value); }
        }
        string fUUID;
        [Size(SizeAttribute.Unlimited)]
        public string UUID
        {
            get { return fUUID; }
            set { SetPropertyValue<string>(nameof(UUID), ref fUUID, value); }
        }
        DateTime fFecha_CFDI;
        public DateTime Fecha_CFDI
        {
            get { return fFecha_CFDI; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_CFDI), ref fFecha_CFDI, value); }
        }
        DateTime fFecha_Timbrado;
        public DateTime Fecha_Timbrado
        {
            get { return fFecha_Timbrado; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_Timbrado), ref fFecha_Timbrado, value); }
        }
        decimal fSubtotal;
        public decimal Subtotal
        {
            get { return fSubtotal; }
            set { SetPropertyValue<decimal>(nameof(Subtotal), ref fSubtotal, value); }
        }
        decimal fRetenciones;
        public decimal Retenciones
        {
            get { return fRetenciones; }
            set { SetPropertyValue<decimal>(nameof(Retenciones), ref fRetenciones, value); }
        }
        decimal fTotal;
        public decimal Total
        {
            get { return fTotal; }
            set { SetPropertyValue<decimal>(nameof(Total), ref fTotal, value); }
        }
        int fPk_Status;
        public int Pk_Status
        {
            get { return fPk_Status; }
            set { SetPropertyValue<int>(nameof(Pk_Status), ref fPk_Status, value); }
        }
    }

}
