//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SistFacturacion.Areas.Facturacion.Models.sistemafactura
{

    [Persistent(@"Tbl_Clientes")]
    public partial class Clientes : XPLiteObject
    {
        int fPk_Cliente;
        [Key(true)]
        public int Pk_Cliente
        {
            get { return fPk_Cliente; }
            set { SetPropertyValue<int>(nameof(Pk_Cliente), ref fPk_Cliente, value); }
        }
        string fRazonSocial;
        [Size(SizeAttribute.Unlimited)]
        public string RazonSocial
        {
            get { return fRazonSocial; }
            set { SetPropertyValue<string>(nameof(RazonSocial), ref fRazonSocial, value); }
        }
        string fDenominacion;
        [Size(SizeAttribute.Unlimited)]
        public string Denominacion
        {
            get { return fDenominacion; }
            set { SetPropertyValue<string>(nameof(Denominacion), ref fDenominacion, value); }
        }
        string fRFC;
        [Size(13)]
        public string RFC
        {
            get { return fRFC; }
            set { SetPropertyValue<string>(nameof(RFC), ref fRFC, value); }
        }
        string fCalle;
        [Size(SizeAttribute.Unlimited)]
        public string Calle
        {
            get { return fCalle; }
            set { SetPropertyValue<string>(nameof(Calle), ref fCalle, value); }
        }
        string fInterior;
        [Size(10)]
        public string Interior
        {
            get { return fInterior; }
            set { SetPropertyValue<string>(nameof(Interior), ref fInterior, value); }
        }
        string fExterior;
        [Size(10)]
        public string Exterior
        {
            get { return fExterior; }
            set { SetPropertyValue<string>(nameof(Exterior), ref fExterior, value); }
        }
        string fColonia;
        [Size(10)]
        public string Colonia
        {
            get { return fColonia; }
            set { SetPropertyValue<string>(nameof(Colonia), ref fColonia, value); }
        }
        string fCP;
        [Size(10)]
        public string CP
        {
            get { return fCP; }
            set { SetPropertyValue<string>(nameof(CP), ref fCP, value); }
        }
        int fPk_Empresa;
        public int Pk_Empresa
        {
            get { return fPk_Empresa; }
            set { SetPropertyValue<int>(nameof(Pk_Empresa), ref fPk_Empresa, value); }
        }
    }

}
