//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SistFacturacion.Areas.Facturacion.Models.sistemafactura
{

    [Persistent(@"Tbl_Empresas")]
    public partial class Empresas : XPLiteObject
    {
        int fPk_Empresa;
        [Key(true)]
        public int Pk_Empresa
        {
            get { return fPk_Empresa; }
            set { SetPropertyValue<int>(nameof(Pk_Empresa), ref fPk_Empresa, value); }
        }
        string fRFC;
        [Size(13)]
        public string RFC
        {
            get { return fRFC; }
            set { SetPropertyValue<string>(nameof(RFC), ref fRFC, value); }
        }
        string fDenominacion;
        [Size(128)]
        public string Denominacion
        {
            get { return fDenominacion; }
            set { SetPropertyValue<string>(nameof(Denominacion), ref fDenominacion, value); }
        }
        string fArchivo_Cert;
        [Size(SizeAttribute.Unlimited)]
        public string Archivo_Cert
        {
            get { return fArchivo_Cert; }
            set { SetPropertyValue<string>(nameof(Archivo_Cert), ref fArchivo_Cert, value); }
        }
        string fArchivo_Key;
        [Size(SizeAttribute.Unlimited)]
        public string Archivo_Key
        {
            get { return fArchivo_Key; }
            set { SetPropertyValue<string>(nameof(Archivo_Key), ref fArchivo_Key, value); }
        }
        string fLlave;
        [Size(SizeAttribute.Unlimited)]
        public string Llave
        {
            get { return fLlave; }
            set { SetPropertyValue<string>(nameof(Llave), ref fLlave, value); }
        }
        DateTime? fInicio;
        public DateTime? Inicio
        {
            get { return fInicio; }
            set { SetPropertyValue<DateTime?>(nameof(Inicio), ref fInicio, value); }
        }
        DateTime? fFin;
        public DateTime? Fin
        {
            get { return fFin; }
            set { SetPropertyValue<DateTime?>(nameof(Fin), ref fFin, value); }
        }
    }

}
