//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SistFacturacion.Areas.Facturacion.Models.sistemafactura
{

    [Persistent(@"Tbl_Series")]
    public partial class Series : XPLiteObject
    {
        int fPk_Serie;
        [Key(true)]
        public int Pk_Serie
        {
            get { return fPk_Serie; }
            set { SetPropertyValue<int>(nameof(Pk_Serie), ref fPk_Serie, value); }
        }
        int fPk_Empresa;
        public int Pk_Empresa
        {
            get { return fPk_Empresa; }
            set { SetPropertyValue<int>(nameof(Pk_Empresa), ref fPk_Empresa, value); }
        }
        string fSerie;
        [Size(SizeAttribute.Unlimited)]
        public string Serie
        {
            get { return fSerie; }
            set { SetPropertyValue<string>(nameof(Serie), ref fSerie, value); }
        }
        int fFolio;
        public int Folio
        {
            get { return fFolio; }
            set { SetPropertyValue<int>(nameof(Folio), ref fFolio, value); }
        }
    }

}
