//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace SistFacturacion.Areas.Facturacion.Models.sistemafactura
{

    [Persistent(@"Tbl_Usuarios")]
    public partial class Usuarios : XPLiteObject
    {
        int fPk_Usuario;
        [Key]
        public int Pk_Usuario
        {
            get { return fPk_Usuario; }
            set { SetPropertyValue<int>(nameof(Pk_Usuario), ref fPk_Usuario, value); }
        }
        string fPermisos;
        [Size(SizeAttribute.Unlimited)]
        public string Permisos
        {
            get { return fPermisos; }
            set { SetPropertyValue<string>(nameof(Permisos), ref fPermisos, value); }
        }
        string fUsuario;
        [Size(SizeAttribute.Unlimited)]
        public string Usuario
        {
            get { return fUsuario; }
            set { SetPropertyValue<string>(nameof(Usuario), ref fUsuario, value); }
        }
    }

}
